### ISSUE TITLE
GPytorch import error

### ISSUE THREAD

**Issue by mingyin1994** [cornellius-gp/gpytorch#409]
I installed gpytorch, but when I use import gpytorch it told me cannot import name '_standard_normal'. I have pytorch installed correctly, anyone know how to deal with this issue?
<img width="571" alt="screen shot 2018-12-01 at 12 59 15 pm" src="https://user-images.githubusercontent.com/39140136/49332817-f922a000-f568-11e8-8f45-35c94853ae80.png">

**Comment by gpleiss** [comment]
This sounds like you're using PyTorch 0.4. GPyTorch only works with PyTorch 1.0. You should install `pytorch_nightly`.
